#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <strings.h>
#include <va/va.h>
#include <va/va_enc_h264.h>
#include <va/va_enc_hevc.h>
#include <va/va_enc_av1.h>

#define SZ(T, n) printf("\t%s = %zu\n", n, sizeof(T))
#define OFF(T, f, n) printf("\t%s = %zu\n", n, offsetof(T, f))
/* BIT prints the bit position of a bitfield inside its union's value. */
#define BIT(T, u, f, n) do { T s; memset(&s, 0, sizeof s); s.u.bits.f = 1; printf("\t%s = %d\n", n, ffs(s.u.value) - 1); } while (0)
#define UBIT(T, f, n) do { T u; u.value = 0; u.bits.f = 1; printf("\t%s = %d\n", n, ffs(u.value) - 1); } while (0)
#define C(v, n) printf("\t%s = %ld\n", n, (long)(v))

int main(void) {
	printf("//go:build linux && (amd64 || arm64)\n\npackage hwenc\n\n// Code generated by testdata/vaoff.c from the libva headers; DO NOT EDIT.\n// See TestVAAPILayout.\n\nconst (\n");
	C(VA_STATUS_SUCCESS, "vaStatusSuccess"); C(VAProfileH264High, "vaProfileH264High"); C(VAProfileHEVCMain, "vaProfileHEVCMain");
	C(VAEntrypointEncSlice, "vaEntrypointEncSlice"); C(VAEntrypointEncSliceLP, "vaEntrypointEncSliceLP");
	C(VAConfigAttribRTFormat, "vaConfigAttribRTFormat"); C(VAConfigAttribRateControl, "vaConfigAttribRateControl"); C(VAConfigAttribEncPackedHeaders, "vaConfigAttribEncPackedHeaders");
	C(VAConfigAttribEncMaxRefFrames, "vaConfigAttribEncMaxRefFrames"); C(VAConfigAttribPredictionDirection, "vaConfigAttribPredictionDirection"); C(VA_ATTRIB_NOT_SUPPORTED, "vaAttribNotSupported");
	C(VA_RC_CQP, "vaRCCQP"); C(VA_RT_FORMAT_YUV420, "vaRTFormatYUV420"); C(VA_PROGRESSIVE, "vaProgressive"); C(VA_INVALID_ID, "vaInvalidID"); C(VA_INVALID_SURFACE, "vaInvalidSurface");
	C(VA_ENC_PACKED_HEADER_SEQUENCE, "vaPackedSeqFlag"); C(VA_ENC_PACKED_HEADER_PICTURE, "vaPackedPicFlag"); C(VA_ENC_PACKED_HEADER_SLICE, "vaPackedSliceFlag");
	C(VA_PREDICTION_DIRECTION_PREVIOUS, "vaPredictionPrevious"); C(VA_PREDICTION_DIRECTION_FUTURE, "vaPredictionFuture"); C(VA_PREDICTION_DIRECTION_BI_NOT_EMPTY, "vaPredictionBiNotEmpty");
	C(VAEncCodedBufferType, "vaEncCodedBufferType"); C(VAEncSequenceParameterBufferType, "vaEncSequenceParameterBufferType"); C(VAEncPictureParameterBufferType, "vaEncPictureParameterBufferType");
	C(VAEncSliceParameterBufferType, "vaEncSliceParameterBufferType"); C(VAEncPackedHeaderParameterBufferType, "vaEncPackedHeaderParameterBufferType"); C(VAEncPackedHeaderDataBufferType, "vaEncPackedHeaderDataBufferType");
	C(VAEncPackedHeaderSequence, "vaEncPackedHeaderSequence"); C(VAEncPackedHeaderPicture, "vaEncPackedHeaderPicture"); C(VAEncPackedHeaderSlice, "vaEncPackedHeaderSlice");
	C(VAConfigAttribEncHEVCFeatures, "vaConfigAttribEncHEVCFeatures"); C(VAConfigAttribEncHEVCBlockSizes, "vaConfigAttribEncHEVCBlockSizes"); C(VA_FEATURE_NOT_SUPPORTED, "vaFeatureNotSupported"); C(VA_FEATURE_REQUIRED, "vaFeatureRequired");
	C(VA_PICTURE_H264_INVALID, "vaPictureH264Invalid"); C(VA_PICTURE_H264_SHORT_TERM_REFERENCE, "vaPictureH264ShortTermRef");
	C(VA_PICTURE_HEVC_INVALID, "vaPictureHEVCInvalid"); C(VA_PICTURE_HEVC_RPS_ST_CURR_BEFORE, "vaPictureHEVCStCurrBefore"); C(VA_PICTURE_HEVC_RPS_ST_CURR_AFTER, "vaPictureHEVCStCurrAfter");
	C(VA_FOURCC_NV12, "vaFourccNV12"); C(VA_CODED_BUF_STATUS_SLICE_OVERFLOW_MASK, "vaCodedSliceOverflow");

	SZ(VAConfigAttrib, "vaSizeConfigAttrib");
	typedef VAConfigAttribValEncHEVCFeatures F;
	UBIT(F, amp, "vaHEVCFeatAMPBit"); UBIT(F, sao, "vaHEVCFeatSAOBit"); UBIT(F, temporal_mvp, "vaHEVCFeatTMVPBit");
	UBIT(F, strong_intra_smoothing, "vaHEVCFeatStrongIntraBit"); UBIT(F, sign_data_hiding, "vaHEVCFeatSignHidingBit");
	UBIT(F, transform_skip, "vaHEVCFeatTransformSkipBit"); UBIT(F, cu_qp_delta, "vaHEVCFeatCUQPDeltaBit");
	typedef VAConfigAttribValEncHEVCBlockSizes B;
	UBIT(B, log2_max_coding_tree_block_size_minus3, "vaHEVCBlkMaxCTBBit"); UBIT(B, log2_min_coding_tree_block_size_minus3, "vaHEVCBlkMinCTBBit");
	UBIT(B, log2_min_luma_coding_block_size_minus3, "vaHEVCBlkMinCBBit");
	UBIT(B, log2_max_luma_transform_block_size_minus2, "vaHEVCBlkMaxTBBit"); UBIT(B, log2_min_luma_transform_block_size_minus2, "vaHEVCBlkMinTBBit");
	UBIT(B, max_max_transform_hierarchy_depth_inter, "vaHEVCBlkMaxTHDInterBit"); UBIT(B, max_max_transform_hierarchy_depth_intra, "vaHEVCBlkMaxTHDIntraBit");
	SZ(VAImage, "vaSizeImage");
	OFF(VAImage, format.fourcc, "vaImageFourcc"); OFF(VAImage, image_id, "vaImageID"); OFF(VAImage, buf, "vaImageBuf");
	OFF(VAImage, num_planes, "vaImageNumPlanes"); OFF(VAImage, pitches, "vaImagePitches"); OFF(VAImage, offsets, "vaImageOffsets");
	OFF(VAImage, width, "vaImageWidth"); OFF(VAImage, height, "vaImageHeight");
	OFF(VACodedBufferSegment, size, "vaSegSize"); OFF(VACodedBufferSegment, status, "vaSegStatus");
	OFF(VACodedBufferSegment, buf, "vaSegBuf"); OFF(VACodedBufferSegment, next, "vaSegNext");
	SZ(VAEncPackedHeaderParameterBuffer, "vaSizePackedHeaderParam");
	OFF(VAEncPackedHeaderParameterBuffer, type, "vaPackedType"); OFF(VAEncPackedHeaderParameterBuffer, bit_length, "vaPackedBitLength");
	OFF(VAEncPackedHeaderParameterBuffer, has_emulation_bytes, "vaPackedHasEmulation");

	/* H.264 */
	SZ(VAPictureH264, "vaSizePictureH264");
	OFF(VAPictureH264, picture_id, "vaH264PicID"); OFF(VAPictureH264, frame_idx, "vaH264PicFrameIdx");
	OFF(VAPictureH264, flags, "vaH264PicFlags"); OFF(VAPictureH264, TopFieldOrderCnt, "vaH264PicTopPOC");
	OFF(VAPictureH264, BottomFieldOrderCnt, "vaH264PicBottomPOC");
	typedef VAEncSequenceParameterBufferH264 S;
	SZ(S, "vaSizeH264Seq");
	OFF(S, seq_parameter_set_id, "vaH264SeqID"); OFF(S, level_idc, "vaH264SeqLevel"); OFF(S, intra_period, "vaH264SeqIntraPeriod");
	OFF(S, intra_idr_period, "vaH264SeqIDRPeriod"); OFF(S, ip_period, "vaH264SeqIPPeriod"); OFF(S, max_num_ref_frames, "vaH264SeqMaxRefs");
	OFF(S, picture_width_in_mbs, "vaH264SeqWidthMBs"); OFF(S, picture_height_in_mbs, "vaH264SeqHeightMBs");
	OFF(S, seq_fields, "vaH264SeqFields");
	BIT(S, seq_fields, chroma_format_idc, "vaH264SeqChromaFormatBit"); BIT(S, seq_fields, frame_mbs_only_flag, "vaH264SeqFrameMBsOnlyBit");
	BIT(S, seq_fields, direct_8x8_inference_flag, "vaH264SeqDirect8x8Bit"); BIT(S, seq_fields, log2_max_frame_num_minus4, "vaH264SeqLog2MaxFrameNumBit");
	BIT(S, seq_fields, pic_order_cnt_type, "vaH264SeqPOCTypeBit"); BIT(S, seq_fields, log2_max_pic_order_cnt_lsb_minus4, "vaH264SeqLog2MaxPOCLsbBit");
	OFF(S, frame_cropping_flag, "vaH264SeqCropping"); OFF(S, frame_crop_right_offset, "vaH264SeqCropRight"); OFF(S, frame_crop_bottom_offset, "vaH264SeqCropBottom");
	OFF(S, vui_parameters_present_flag, "vaH264SeqVUI"); OFF(S, vui_fields, "vaH264SeqVUIFields");
	BIT(S, vui_fields, timing_info_present_flag, "vaH264SeqTimingBit"); BIT(S, vui_fields, fixed_frame_rate_flag, "vaH264SeqFixedRateBit");
	BIT(S, vui_fields, bitstream_restriction_flag, "vaH264SeqRestrictionBit");
	BIT(S, vui_fields, log2_max_mv_length_horizontal, "vaH264SeqMVHorBit"); BIT(S, vui_fields, log2_max_mv_length_vertical, "vaH264SeqMVVerBit");
	BIT(S, vui_fields, motion_vectors_over_pic_boundaries_flag, "vaH264SeqMVBoundBit");
	OFF(S, num_units_in_tick, "vaH264SeqUnitsInTick"); OFF(S, time_scale, "vaH264SeqTimeScale");
	typedef VAEncPictureParameterBufferH264 P;
	SZ(P, "vaSizeH264Pic");
	OFF(P, CurrPic, "vaH264PicCurr"); OFF(P, ReferenceFrames, "vaH264PicRefs"); OFF(P, coded_buf, "vaH264PicCodedBuf");
	OFF(P, pic_parameter_set_id, "vaH264PicPPSID"); OFF(P, seq_parameter_set_id, "vaH264PicSPSID"); OFF(P, last_picture, "vaH264PicLast");
	OFF(P, frame_num, "vaH264PicFrameNum"); OFF(P, pic_init_qp, "vaH264PicInitQP");
	OFF(P, num_ref_idx_l0_active_minus1, "vaH264PicNumRefL0"); OFF(P, num_ref_idx_l1_active_minus1, "vaH264PicNumRefL1");
	OFF(P, pic_fields, "vaH264PicFields");
	BIT(P, pic_fields, idr_pic_flag, "vaH264PicIDRBit"); BIT(P, pic_fields, reference_pic_flag, "vaH264PicRefBit");
	BIT(P, pic_fields, entropy_coding_mode_flag, "vaH264PicCABACBit"); BIT(P, pic_fields, transform_8x8_mode_flag, "vaH264PicT8x8Bit");
	BIT(P, pic_fields, deblocking_filter_control_present_flag, "vaH264PicDeblockCtlBit");
	typedef VAEncSliceParameterBufferH264 L;
	SZ(L, "vaSizeH264Slice");
	OFF(L, macroblock_address, "vaH264SliceMBAddr"); OFF(L, num_macroblocks, "vaH264SliceNumMBs"); OFF(L, macroblock_info, "vaH264SliceMBInfo");
	OFF(L, slice_type, "vaH264SliceType"); OFF(L, pic_parameter_set_id, "vaH264SlicePPSID"); OFF(L, idr_pic_id, "vaH264SliceIDRID");
	OFF(L, pic_order_cnt_lsb, "vaH264SlicePOCLsb"); OFF(L, direct_spatial_mv_pred_flag, "vaH264SliceDirectSpatial");
	OFF(L, num_ref_idx_active_override_flag, "vaH264SliceOverride");
	OFF(L, num_ref_idx_l0_active_minus1, "vaH264SliceNumRefL0"); OFF(L, num_ref_idx_l1_active_minus1, "vaH264SliceNumRefL1");
	OFF(L, RefPicList0, "vaH264SliceRefList0"); OFF(L, RefPicList1, "vaH264SliceRefList1");
	OFF(L, slice_qp_delta, "vaH264SliceQPDelta");

	/* HEVC */
	SZ(VAPictureHEVC, "vaSizePictureHEVC");
	OFF(VAPictureHEVC, picture_id, "vaHEVCPicID"); OFF(VAPictureHEVC, pic_order_cnt, "vaHEVCPicPOC"); OFF(VAPictureHEVC, flags, "vaHEVCPicFlags");
	typedef VAEncSequenceParameterBufferHEVC HS;
	SZ(HS, "vaSizeHEVCSeq");
	OFF(HS, general_profile_idc, "vaHEVCSeqProfile"); OFF(HS, general_level_idc, "vaHEVCSeqLevel"); OFF(HS, general_tier_flag, "vaHEVCSeqTier");
	OFF(HS, intra_period, "vaHEVCSeqIntraPeriod"); OFF(HS, intra_idr_period, "vaHEVCSeqIDRPeriod"); OFF(HS, ip_period, "vaHEVCSeqIPPeriod");
	OFF(HS, pic_width_in_luma_samples, "vaHEVCSeqWidth"); OFF(HS, pic_height_in_luma_samples, "vaHEVCSeqHeight");
	OFF(HS, seq_fields, "vaHEVCSeqFields");
	BIT(HS, seq_fields, chroma_format_idc, "vaHEVCSeqChromaFormatBit"); BIT(HS, seq_fields, amp_enabled_flag, "vaHEVCSeqAMPBit");
	BIT(HS, seq_fields, sample_adaptive_offset_enabled_flag, "vaHEVCSeqSAOBit"); BIT(HS, seq_fields, sps_temporal_mvp_enabled_flag, "vaHEVCSeqTMVPBit");
	BIT(HS, seq_fields, strong_intra_smoothing_enabled_flag, "vaHEVCSeqStrongIntraBit"); BIT(HS, seq_fields, low_delay_seq, "vaHEVCSeqLowDelayBit");
	OFF(HS, log2_min_luma_coding_block_size_minus3, "vaHEVCSeqLog2MinCB"); OFF(HS, log2_diff_max_min_luma_coding_block_size, "vaHEVCSeqLog2DiffCB");
	OFF(HS, log2_min_transform_block_size_minus2, "vaHEVCSeqLog2MinTB"); OFF(HS, log2_diff_max_min_transform_block_size, "vaHEVCSeqLog2DiffTB");
	OFF(HS, max_transform_hierarchy_depth_inter, "vaHEVCSeqTHDInter"); OFF(HS, max_transform_hierarchy_depth_intra, "vaHEVCSeqTHDIntra");
	OFF(HS, vui_parameters_present_flag, "vaHEVCSeqVUI"); OFF(HS, vui_fields, "vaHEVCSeqVUIFields");
	BIT(HS, vui_fields, vui_timing_info_present_flag, "vaHEVCSeqTimingBit"); BIT(HS, vui_fields, bitstream_restriction_flag, "vaHEVCSeqRestrictionBit");
	BIT(HS, vui_fields, motion_vectors_over_pic_boundaries_flag, "vaHEVCSeqMVBoundBit");
	BIT(HS, vui_fields, log2_max_mv_length_horizontal, "vaHEVCSeqMVHorBit"); BIT(HS, vui_fields, log2_max_mv_length_vertical, "vaHEVCSeqMVVerBit");
	OFF(HS, vui_num_units_in_tick, "vaHEVCSeqUnitsInTick"); OFF(HS, vui_time_scale, "vaHEVCSeqTimeScale");
	typedef VAEncPictureParameterBufferHEVC HP;
	SZ(HP, "vaSizeHEVCPic");
	OFF(HP, decoded_curr_pic, "vaHEVCPicCurr"); OFF(HP, reference_frames, "vaHEVCPicRefs"); OFF(HP, coded_buf, "vaHEVCPicCodedBuf");
	OFF(HP, collocated_ref_pic_index, "vaHEVCPicCollocated"); OFF(HP, last_picture, "vaHEVCPicLast"); OFF(HP, pic_init_qp, "vaHEVCPicInitQP");
	OFF(HP, diff_cu_qp_delta_depth, "vaHEVCPicDiffCUQPDepth");
	OFF(HP, num_ref_idx_l0_default_active_minus1, "vaHEVCPicNumRefL0"); OFF(HP, num_ref_idx_l1_default_active_minus1, "vaHEVCPicNumRefL1");
	OFF(HP, slice_pic_parameter_set_id, "vaHEVCPicPPSID"); OFF(HP, nal_unit_type, "vaHEVCPicNALType");
	OFF(HP, pic_fields, "vaHEVCPicFields");
	BIT(HP, pic_fields, idr_pic_flag, "vaHEVCPicIDRBit"); BIT(HP, pic_fields, coding_type, "vaHEVCPicCodingTypeBit");
	BIT(HP, pic_fields, reference_pic_flag, "vaHEVCPicRefBit"); BIT(HP, pic_fields, cu_qp_delta_enabled_flag, "vaHEVCPicCUQPDeltaBit");
	BIT(HP, pic_fields, transform_skip_enabled_flag, "vaHEVCPicTransformSkipBit");
	BIT(HP, pic_fields, sign_data_hiding_enabled_flag, "vaHEVCPicSignHidingBit");
	BIT(HP, pic_fields, pps_loop_filter_across_slices_enabled_flag, "vaHEVCPicLFAcrossSlicesBit");
	typedef VAEncSliceParameterBufferHEVC HL;
	SZ(HL, "vaSizeHEVCSlice");
	OFF(HL, slice_segment_address, "vaHEVCSliceAddr"); OFF(HL, num_ctu_in_slice, "vaHEVCSliceNumCTUs"); OFF(HL, slice_type, "vaHEVCSliceType");
	OFF(HL, slice_pic_parameter_set_id, "vaHEVCSlicePPSID");
	OFF(HL, num_ref_idx_l0_active_minus1, "vaHEVCSliceNumRefL0"); OFF(HL, num_ref_idx_l1_active_minus1, "vaHEVCSliceNumRefL1");
	OFF(HL, ref_pic_list0, "vaHEVCSliceRefList0"); OFF(HL, ref_pic_list1, "vaHEVCSliceRefList1");
	OFF(HL, max_num_merge_cand, "vaHEVCSliceMaxMerge"); OFF(HL, slice_qp_delta, "vaHEVCSliceQPDelta");
	OFF(HL, slice_fields, "vaHEVCSliceFields");
	BIT(HL, slice_fields, last_slice_of_pic_flag, "vaHEVCSliceLastBit"); BIT(HL, slice_fields, slice_temporal_mvp_enabled_flag, "vaHEVCSliceTMVPBit");
	BIT(HL, slice_fields, slice_sao_luma_flag, "vaHEVCSliceSAOLumaBit"); BIT(HL, slice_fields, slice_sao_chroma_flag, "vaHEVCSliceSAOChromaBit");
	BIT(HL, slice_fields, num_ref_idx_active_override_flag, "vaHEVCSliceOverrideBit");
	BIT(HL, slice_fields, slice_loop_filter_across_slices_enabled_flag, "vaHEVCSliceLFAcrossBit");
	BIT(HL, slice_fields, collocated_from_l0_flag, "vaHEVCSliceColFromL0Bit");

	/* AV1 */
	C(VAProfileAV1Profile0, "vaProfileAV1Profile0");
	typedef VAEncSequenceParameterBufferAV1 AS;
	SZ(AS, "vaSizeAV1Seq");
	OFF(AS, seq_profile, "vaAV1SeqProfile"); OFF(AS, seq_level_idx, "vaAV1SeqLevel"); OFF(AS, seq_tier, "vaAV1SeqTier");
	OFF(AS, intra_period, "vaAV1SeqIntraPeriod"); OFF(AS, ip_period, "vaAV1SeqIPPeriod");
	OFF(AS, seq_fields, "vaAV1SeqFields"); OFF(AS, order_hint_bits_minus_1, "vaAV1SeqOrderHintBits");
	BIT(AS, seq_fields, enable_order_hint, "vaAV1SeqOrderHintBit"); BIT(AS, seq_fields, enable_cdef, "vaAV1SeqCDEFBit");
	typedef VAEncPictureParameterBufferAV1 AP;
	SZ(AP, "vaSizeAV1Pic");
	OFF(AP, frame_width_minus_1, "vaAV1PicWidth"); OFF(AP, frame_height_minus_1, "vaAV1PicHeight");
	OFF(AP, reconstructed_frame, "vaAV1PicRecon"); OFF(AP, coded_buf, "vaAV1PicCodedBuf");
	OFF(AP, reference_frames, "vaAV1PicRefs"); OFF(AP, ref_frame_idx, "vaAV1PicRefIdx");
	OFF(AP, primary_ref_frame, "vaAV1PicPrimaryRef"); OFF(AP, order_hint, "vaAV1PicOrderHint");
	OFF(AP, refresh_frame_flags, "vaAV1PicRefresh"); OFF(AP, ref_frame_ctrl_l0, "vaAV1PicRefCtrlL0");
	OFF(AP, picture_flags, "vaAV1PicFlags");
	BIT(AP, picture_flags, frame_type, "vaAV1PicFrameTypeBit"); BIT(AP, picture_flags, error_resilient_mode, "vaAV1PicErrorResilientBit");
	OFF(AP, base_qindex, "vaAV1PicBaseQIndex"); OFF(AP, min_base_qindex, "vaAV1PicMinQIndex"); OFF(AP, max_base_qindex, "vaAV1PicMaxQIndex");
	OFF(AP, mode_control_flags, "vaAV1PicModeControl"); BIT(AP, mode_control_flags, tx_mode, "vaAV1PicTxModeBit");
	OFF(AP, tile_cols, "vaAV1PicTileCols"); OFF(AP, tile_rows, "vaAV1PicTileRows");
	OFF(AP, width_in_sbs_minus_1, "vaAV1PicWidthSBs"); OFF(AP, height_in_sbs_minus_1, "vaAV1PicHeightSBs");
	OFF(AP, bit_offset_qindex, "vaAV1PicBitOffsetQIndex"); OFF(AP, bit_offset_segmentation, "vaAV1PicBitOffsetSeg");
	OFF(AP, bit_offset_loopfilter_params, "vaAV1PicBitOffsetLF"); OFF(AP, bit_offset_cdef_params, "vaAV1PicBitOffsetCDEF");
	OFF(AP, size_in_bits_cdef_params, "vaAV1PicCDEFBits"); OFF(AP, byte_offset_frame_hdr_obu_size, "vaAV1PicOBUSizeOffset");
	OFF(AP, size_in_bits_frame_hdr_obu, "vaAV1PicFrameHdrBits"); OFF(AP, tile_group_obu_hdr_info, "vaAV1PicTGHeader");
	{ AP p; memset(&p, 0, sizeof p); p.tile_group_obu_hdr_info.bits.obu_has_size_field = 1; printf("\t%s = %d\n", "vaAV1TGHasSizeBit", ffs(p.tile_group_obu_hdr_info.value) - 1); }
	{ VARefFrameCtrlAV1 c; c.value = 0; c.fields.search_idx0 = 1; printf("\t%s = %d\n", "vaAV1SearchIdx0Bit", ffs(c.value) - 1); }
	SZ(VAEncTileGroupBufferAV1, "vaSizeAV1TileGroup");
	printf(")\n");
	return 0;
}
