//go:build linux && (amd64 || arm64)

package gpu

// Code generated by testdata/nvdecoff.c from nv-codec-headers (cuviddec.h,
// nvcuvid.h, n12.0.16.1); DO NOT EDIT. See TestNVDECLayout. The offsets are
// 64-bit Linux's, where tcu_ulong is an 8-byte unsigned long; Windows' differ.

const (
	cuvSizeParserParams    = 136
	cuvPPCodec             = 0
	cuvPPMaxSurfaces       = 4
	cuvPPClockRate         = 8
	cuvPPErrorThreshold    = 12
	cuvPPDisplayDelay      = 16
	cuvPPUserData          = 40
	cuvPPSequence          = 48
	cuvPPDecode            = 56
	cuvPPDisplay           = 64
	cuvPPSEI               = 80
	cuvSizePacket          = 32
	cuvPktFlags            = 0
	cuvPktSize             = 8
	cuvPktPayload          = 16
	cuvPktTimestamp        = 24
	cuvPktEOS              = 1
	cuvPktHasTimestamp     = 2
	cuvPktEndOfPicture     = 8
	cuvFmtCodec            = 0
	cuvFmtRateNum          = 4
	cuvFmtRateDen          = 8
	cuvFmtProgressive      = 12
	cuvFmtDepthLuma        = 13
	cuvFmtDepthChroma      = 14
	cuvFmtMinSurfaces      = 15
	cuvFmtCodedWidth       = 16
	cuvFmtCodedHeight      = 20
	cuvFmtLeft             = 24
	cuvFmtTop              = 28
	cuvFmtRight            = 32
	cuvFmtBottom           = 36
	cuvFmtChroma           = 40
	cuvFmtPrimaries        = 57
	cuvFmtTransfer         = 58
	cuvFmtMatrix           = 59
	cuvFmtSignalFlags      = 56
	cuvFmtFullRangeMask    = 8
	cuvSizeCreateInfo      = 176
	cuvCIWidth             = 0
	cuvCIHeight            = 8
	cuvCISurfaces          = 16
	cuvCICodec             = 24
	cuvCIChroma            = 28
	cuvCIFlags             = 32
	cuvCIDepth             = 40
	cuvCIMaxWidth          = 56
	cuvCIMaxHeight         = 64
	cuvCIDisplayArea       = 80
	cuvCIOutputFormat      = 88
	cuvCIDeinterlace       = 92
	cuvCITargetWidth       = 96
	cuvCITargetHeight      = 104
	cuvCIOutputSurfaces    = 112
	cuvCILock              = 120
	cuvSizeDispInfo        = 24
	cuvDIIndex             = 0
	cuvDIProgressive       = 4
	cuvDITopFirst          = 8
	cuvDITimestamp         = 16
	cuvSizeProcParams      = 264
	cuvPPProgressive       = 0
	cuvPPTopFirst          = 8
	cuvPicCurrIdx          = 8
	cuvSizeCaps            = 88
	cuvCapsCodec           = 0
	cuvCapsChroma          = 4
	cuvCapsDepth           = 8
	cuvCapsSupported       = 24
	cuvCapsMaxWidth        = 28
	cuvCapsMaxHeight       = 32
	cuvCapsOutputMask      = 26
	cuSizeMemcpy2D         = 128
	cuMCSrcType            = 16
	cuMCSrcDevice          = 32
	cuMCSrcPitch           = 48
	cuMCSrcY               = 8
	cuMCDstType            = 72
	cuMCDstHost            = 80
	cuMCDstPitch           = 104
	cuMCWidth              = 112
	cuMCHeight             = 120
	cuMemoryHost           = 1
	cuMemoryDevice         = 2
	cuvCodecMPEG2          = 1
	cuvCodecVC1            = 3
	cuvCodecH264           = 4
	cuvCodecHEVC           = 8
	cuvCodecAV1            = 11
	cuvChroma420           = 1
	cuvSurfaceNV12         = 0
	cuvSurfaceP016         = 1
	cuvDeinterlaceWeave    = 0
	cuvDeinterlaceAdaptive = 2
	cuvCreatePreferCUVID   = 4
)
