#include <stdio.h>
#include <stddef.h>
#include <ffnvcodec/dynlink_cuda.h>
#include <ffnvcodec/dynlink_nvcuvid.h>
#define S(T, n) printf("\t%s = %zu\n", n, sizeof(T))
#define O(T, f, n) printf("\t%s = %zu\n", n, offsetof(T, f))
#define C(v, n) printf("\t%s = %ld\n", n, (long)(v))
int main(void) {
	printf("//go:build linux && (amd64 || arm64)\n\npackage gpu\n\n// Code generated by testdata/nvdecoff.c from nv-codec-headers (cuviddec.h,\n// nvcuvid.h, n12.0.16.1); DO NOT EDIT. See TestNVDECLayout. The offsets are\n// 64-bit Linux's, where tcu_ulong is an 8-byte unsigned long; Windows' differ.\n\nconst (\n");
	S(CUVIDPARSERPARAMS, "cuvSizeParserParams");
	O(CUVIDPARSERPARAMS, CodecType, "cuvPPCodec"); O(CUVIDPARSERPARAMS, ulMaxNumDecodeSurfaces, "cuvPPMaxSurfaces");
	O(CUVIDPARSERPARAMS, ulClockRate, "cuvPPClockRate"); O(CUVIDPARSERPARAMS, ulErrorThreshold, "cuvPPErrorThreshold");
	O(CUVIDPARSERPARAMS, ulMaxDisplayDelay, "cuvPPDisplayDelay"); O(CUVIDPARSERPARAMS, pUserData, "cuvPPUserData");
	O(CUVIDPARSERPARAMS, pfnSequenceCallback, "cuvPPSequence"); O(CUVIDPARSERPARAMS, pfnDecodePicture, "cuvPPDecode");
	O(CUVIDPARSERPARAMS, pfnDisplayPicture, "cuvPPDisplay"); O(CUVIDPARSERPARAMS, pfnGetSEIMsg, "cuvPPSEI");
	S(CUVIDSOURCEDATAPACKET, "cuvSizePacket");
	O(CUVIDSOURCEDATAPACKET, flags, "cuvPktFlags"); O(CUVIDSOURCEDATAPACKET, payload_size, "cuvPktSize");
	O(CUVIDSOURCEDATAPACKET, payload, "cuvPktPayload"); O(CUVIDSOURCEDATAPACKET, timestamp, "cuvPktTimestamp");
	C(CUVID_PKT_ENDOFSTREAM, "cuvPktEOS"); C(CUVID_PKT_TIMESTAMP, "cuvPktHasTimestamp"); C(CUVID_PKT_ENDOFPICTURE, "cuvPktEndOfPicture");
	O(CUVIDEOFORMAT, codec, "cuvFmtCodec"); O(CUVIDEOFORMAT, frame_rate.numerator, "cuvFmtRateNum"); O(CUVIDEOFORMAT, frame_rate.denominator, "cuvFmtRateDen");
	O(CUVIDEOFORMAT, progressive_sequence, "cuvFmtProgressive"); O(CUVIDEOFORMAT, bit_depth_luma_minus8, "cuvFmtDepthLuma");
	O(CUVIDEOFORMAT, bit_depth_chroma_minus8, "cuvFmtDepthChroma"); O(CUVIDEOFORMAT, min_num_decode_surfaces, "cuvFmtMinSurfaces");
	O(CUVIDEOFORMAT, coded_width, "cuvFmtCodedWidth"); O(CUVIDEOFORMAT, coded_height, "cuvFmtCodedHeight");
	O(CUVIDEOFORMAT, display_area.left, "cuvFmtLeft"); O(CUVIDEOFORMAT, display_area.top, "cuvFmtTop");
	O(CUVIDEOFORMAT, display_area.right, "cuvFmtRight"); O(CUVIDEOFORMAT, display_area.bottom, "cuvFmtBottom");
	O(CUVIDEOFORMAT, chroma_format, "cuvFmtChroma");
	O(CUVIDEOFORMAT, video_signal_description.color_primaries, "cuvFmtPrimaries");
	O(CUVIDEOFORMAT, video_signal_description.transfer_characteristics, "cuvFmtTransfer");
	O(CUVIDEOFORMAT, video_signal_description.matrix_coefficients, "cuvFmtMatrix");
	{ CUVIDEOFORMAT f = {0}; f.video_signal_description.video_full_range_flag = 1; unsigned char *b = (unsigned char *)&f.video_signal_description;
	  printf("\tcuvFmtSignalFlags = %zu\n", offsetof(CUVIDEOFORMAT, video_signal_description)); printf("\tcuvFmtFullRangeMask = %d\n", b[0]); }
	S(CUVIDDECODECREATEINFO, "cuvSizeCreateInfo");
	O(CUVIDDECODECREATEINFO, ulWidth, "cuvCIWidth"); O(CUVIDDECODECREATEINFO, ulHeight, "cuvCIHeight");
	O(CUVIDDECODECREATEINFO, ulNumDecodeSurfaces, "cuvCISurfaces"); O(CUVIDDECODECREATEINFO, CodecType, "cuvCICodec");
	O(CUVIDDECODECREATEINFO, ChromaFormat, "cuvCIChroma"); O(CUVIDDECODECREATEINFO, ulCreationFlags, "cuvCIFlags");
	O(CUVIDDECODECREATEINFO, bitDepthMinus8, "cuvCIDepth"); O(CUVIDDECODECREATEINFO, ulMaxWidth, "cuvCIMaxWidth");
	O(CUVIDDECODECREATEINFO, ulMaxHeight, "cuvCIMaxHeight"); O(CUVIDDECODECREATEINFO, display_area.left, "cuvCIDisplayArea");
	O(CUVIDDECODECREATEINFO, OutputFormat, "cuvCIOutputFormat"); O(CUVIDDECODECREATEINFO, DeinterlaceMode, "cuvCIDeinterlace");
	O(CUVIDDECODECREATEINFO, ulTargetWidth, "cuvCITargetWidth"); O(CUVIDDECODECREATEINFO, ulTargetHeight, "cuvCITargetHeight");
	O(CUVIDDECODECREATEINFO, ulNumOutputSurfaces, "cuvCIOutputSurfaces"); O(CUVIDDECODECREATEINFO, vidLock, "cuvCILock");
	S(CUVIDPARSERDISPINFO, "cuvSizeDispInfo");
	O(CUVIDPARSERDISPINFO, picture_index, "cuvDIIndex"); O(CUVIDPARSERDISPINFO, progressive_frame, "cuvDIProgressive");
	O(CUVIDPARSERDISPINFO, top_field_first, "cuvDITopFirst"); O(CUVIDPARSERDISPINFO, timestamp, "cuvDITimestamp");
	S(CUVIDPROCPARAMS, "cuvSizeProcParams");
	O(CUVIDPROCPARAMS, progressive_frame, "cuvPPProgressive"); O(CUVIDPROCPARAMS, top_field_first, "cuvPPTopFirst");
	O(CUVIDPICPARAMS, CurrPicIdx, "cuvPicCurrIdx");
	S(CUVIDDECODECAPS, "cuvSizeCaps");
	O(CUVIDDECODECAPS, eCodecType, "cuvCapsCodec"); O(CUVIDDECODECAPS, eChromaFormat, "cuvCapsChroma");
	O(CUVIDDECODECAPS, nBitDepthMinus8, "cuvCapsDepth"); O(CUVIDDECODECAPS, bIsSupported, "cuvCapsSupported");
	O(CUVIDDECODECAPS, nMaxWidth, "cuvCapsMaxWidth"); O(CUVIDDECODECAPS, nMaxHeight, "cuvCapsMaxHeight");
	O(CUVIDDECODECAPS, nOutputFormatMask, "cuvCapsOutputMask");
	S(CUDA_MEMCPY2D, "cuSizeMemcpy2D");
	O(CUDA_MEMCPY2D, srcMemoryType, "cuMCSrcType"); O(CUDA_MEMCPY2D, srcDevice, "cuMCSrcDevice"); O(CUDA_MEMCPY2D, srcPitch, "cuMCSrcPitch");
	O(CUDA_MEMCPY2D, srcY, "cuMCSrcY");
	O(CUDA_MEMCPY2D, dstMemoryType, "cuMCDstType"); O(CUDA_MEMCPY2D, dstHost, "cuMCDstHost"); O(CUDA_MEMCPY2D, dstPitch, "cuMCDstPitch");
	O(CUDA_MEMCPY2D, WidthInBytes, "cuMCWidth"); O(CUDA_MEMCPY2D, Height, "cuMCHeight");
	C(CU_MEMORYTYPE_HOST, "cuMemoryHost"); C(CU_MEMORYTYPE_DEVICE, "cuMemoryDevice");
	C(cudaVideoCodec_MPEG2, "cuvCodecMPEG2"); C(cudaVideoCodec_VC1, "cuvCodecVC1"); C(cudaVideoCodec_H264, "cuvCodecH264");
	C(cudaVideoCodec_HEVC, "cuvCodecHEVC"); C(cudaVideoCodec_AV1, "cuvCodecAV1");
	C(cudaVideoChromaFormat_420, "cuvChroma420"); C(cudaVideoSurfaceFormat_NV12, "cuvSurfaceNV12"); C(cudaVideoSurfaceFormat_P016, "cuvSurfaceP016");
	C(cudaVideoDeinterlaceMode_Weave, "cuvDeinterlaceWeave"); C(cudaVideoDeinterlaceMode_Adaptive, "cuvDeinterlaceAdaptive");
	C(cudaVideoCreate_PreferCUVID, "cuvCreatePreferCUVID");
	printf(")\n");
	return 0;
}
