#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <strings.h>
#include <va/va.h>
#include <va/va_enc_h264.h>
#include <va/va_enc_hevc.h>
#include <va/va_enc_av1.h>
#include <va/va_dec_hevc.h>

#define SZ(T, n) printf("\t%s = %zu\n", n, sizeof(T))
#define OFF(T, f, n) printf("\t%s = %zu\n", n, offsetof(T, f))
/* BIT prints the bit position of a bitfield inside its union's value. */
#define BIT(T, u, f, n) do { T s; memset(&s, 0, sizeof s); s.u.bits.f = 1; printf("\t%s = %d\n", n, ffs(s.u.value) - 1); } while (0)
#define UBIT(T, f, n) do { T u; u.value = 0; u.bits.f = 1; printf("\t%s = %d\n", n, ffs(u.value) - 1); } while (0)
#define C(v, n) printf("\t%s = %ld\n", n, (long)(v))

int main(void) {
	printf("//go:build linux && (amd64 || arm64)\n\npackage gpu\n\n// Code generated by testdata/vaoff.c from the libva headers; DO NOT EDIT.\n// See TestVAAPILayout.\n\nconst (\n");
	C(VA_STATUS_SUCCESS, "vaStatusSuccess"); C(VAProfileH264High, "vaProfileH264High"); C(VAProfileHEVCMain, "vaProfileHEVCMain");
	C(VAEntrypointEncSlice, "vaEntrypointEncSlice"); C(VAEntrypointEncSliceLP, "vaEntrypointEncSliceLP");
	C(VAConfigAttribRTFormat, "vaConfigAttribRTFormat"); C(VAConfigAttribRateControl, "vaConfigAttribRateControl"); C(VAConfigAttribEncPackedHeaders, "vaConfigAttribEncPackedHeaders");
	C(VAConfigAttribEncMaxRefFrames, "vaConfigAttribEncMaxRefFrames"); C(VAConfigAttribPredictionDirection, "vaConfigAttribPredictionDirection"); C(VA_ATTRIB_NOT_SUPPORTED, "vaAttribNotSupported");
	C(VA_RC_CQP, "vaRCCQP"); C(VA_RT_FORMAT_YUV420, "vaRTFormatYUV420"); C(VA_PROGRESSIVE, "vaProgressive"); C(VA_INVALID_ID, "vaInvalidID"); C(VA_INVALID_SURFACE, "vaInvalidSurface");
	C(VA_ENC_PACKED_HEADER_SEQUENCE, "vaPackedSeqFlag"); C(VA_ENC_PACKED_HEADER_PICTURE, "vaPackedPicFlag"); C(VA_ENC_PACKED_HEADER_SLICE, "vaPackedSliceFlag");
	C(VA_PREDICTION_DIRECTION_PREVIOUS, "vaPredictionPrevious"); C(VA_PREDICTION_DIRECTION_FUTURE, "vaPredictionFuture"); C(VA_PREDICTION_DIRECTION_BI_NOT_EMPTY, "vaPredictionBiNotEmpty");
	C(VAEncCodedBufferType, "vaEncCodedBufferType"); C(VAEncSequenceParameterBufferType, "vaEncSequenceParameterBufferType"); C(VAEncPictureParameterBufferType, "vaEncPictureParameterBufferType");
	C(VAEncSliceParameterBufferType, "vaEncSliceParameterBufferType"); C(VAEncPackedHeaderParameterBufferType, "vaEncPackedHeaderParameterBufferType"); C(VAEncPackedHeaderDataBufferType, "vaEncPackedHeaderDataBufferType");
	C(VAEncPackedHeaderSequence, "vaEncPackedHeaderSequence"); C(VAEncPackedHeaderPicture, "vaEncPackedHeaderPicture"); C(VAEncPackedHeaderSlice, "vaEncPackedHeaderSlice");
	C(VAConfigAttribEncHEVCFeatures, "vaConfigAttribEncHEVCFeatures"); C(VAConfigAttribEncHEVCBlockSizes, "vaConfigAttribEncHEVCBlockSizes"); C(VA_FEATURE_NOT_SUPPORTED, "vaFeatureNotSupported"); C(VA_FEATURE_REQUIRED, "vaFeatureRequired");
	C(VA_PICTURE_H264_INVALID, "vaPictureH264Invalid"); C(VA_PICTURE_H264_SHORT_TERM_REFERENCE, "vaPictureH264ShortTermRef");
	C(VA_PICTURE_HEVC_INVALID, "vaPictureHEVCInvalid"); C(VA_PICTURE_HEVC_RPS_ST_CURR_BEFORE, "vaPictureHEVCStCurrBefore"); C(VA_PICTURE_HEVC_RPS_ST_CURR_AFTER, "vaPictureHEVCStCurrAfter");
	C(VA_FOURCC_NV12, "vaFourccNV12"); C(VA_FOURCC_P010, "vaFourccP010"); C(VA_RT_FORMAT_YUV420_10, "vaRTFormatYUV420_10"); C(VAProfileHEVCMain10, "vaProfileHEVCMain10"); C(VA_CODED_BUF_STATUS_SLICE_OVERFLOW_MASK, "vaCodedSliceOverflow");

	SZ(VAConfigAttrib, "vaSizeConfigAttrib");
	typedef VAConfigAttribValEncHEVCFeatures F;
	UBIT(F, amp, "vaHEVCFeatAMPBit"); UBIT(F, sao, "vaHEVCFeatSAOBit"); UBIT(F, temporal_mvp, "vaHEVCFeatTMVPBit");
	UBIT(F, strong_intra_smoothing, "vaHEVCFeatStrongIntraBit"); UBIT(F, sign_data_hiding, "vaHEVCFeatSignHidingBit");
	UBIT(F, transform_skip, "vaHEVCFeatTransformSkipBit"); UBIT(F, cu_qp_delta, "vaHEVCFeatCUQPDeltaBit");
	typedef VAConfigAttribValEncHEVCBlockSizes B;
	UBIT(B, log2_max_coding_tree_block_size_minus3, "vaHEVCBlkMaxCTBBit"); UBIT(B, log2_min_coding_tree_block_size_minus3, "vaHEVCBlkMinCTBBit");
	UBIT(B, log2_min_luma_coding_block_size_minus3, "vaHEVCBlkMinCBBit");
	UBIT(B, log2_max_luma_transform_block_size_minus2, "vaHEVCBlkMaxTBBit"); UBIT(B, log2_min_luma_transform_block_size_minus2, "vaHEVCBlkMinTBBit");
	UBIT(B, max_max_transform_hierarchy_depth_inter, "vaHEVCBlkMaxTHDInterBit"); UBIT(B, max_max_transform_hierarchy_depth_intra, "vaHEVCBlkMaxTHDIntraBit");
	SZ(VAImage, "vaSizeImage");
	OFF(VAImage, format.fourcc, "vaImageFourcc"); OFF(VAImage, image_id, "vaImageID"); OFF(VAImage, buf, "vaImageBuf");
	OFF(VAImage, num_planes, "vaImageNumPlanes"); OFF(VAImage, pitches, "vaImagePitches"); OFF(VAImage, offsets, "vaImageOffsets");
	OFF(VAImage, width, "vaImageWidth"); OFF(VAImage, height, "vaImageHeight");
	OFF(VACodedBufferSegment, size, "vaSegSize"); OFF(VACodedBufferSegment, status, "vaSegStatus");
	OFF(VACodedBufferSegment, buf, "vaSegBuf"); OFF(VACodedBufferSegment, next, "vaSegNext");
	SZ(VAEncPackedHeaderParameterBuffer, "vaSizePackedHeaderParam");
	OFF(VAEncPackedHeaderParameterBuffer, type, "vaPackedType"); OFF(VAEncPackedHeaderParameterBuffer, bit_length, "vaPackedBitLength");
	OFF(VAEncPackedHeaderParameterBuffer, has_emulation_bytes, "vaPackedHasEmulation");

	/* H.264 */
	SZ(VAPictureH264, "vaSizePictureH264");
	OFF(VAPictureH264, picture_id, "vaH264PicID"); OFF(VAPictureH264, frame_idx, "vaH264PicFrameIdx");
	OFF(VAPictureH264, flags, "vaH264PicFlags"); OFF(VAPictureH264, TopFieldOrderCnt, "vaH264PicTopPOC");
	OFF(VAPictureH264, BottomFieldOrderCnt, "vaH264PicBottomPOC");
	typedef VAEncSequenceParameterBufferH264 S;
	SZ(S, "vaSizeH264Seq");
	OFF(S, seq_parameter_set_id, "vaH264SeqID"); OFF(S, level_idc, "vaH264SeqLevel"); OFF(S, intra_period, "vaH264SeqIntraPeriod");
	OFF(S, intra_idr_period, "vaH264SeqIDRPeriod"); OFF(S, ip_period, "vaH264SeqIPPeriod"); OFF(S, max_num_ref_frames, "vaH264SeqMaxRefs");
	OFF(S, picture_width_in_mbs, "vaH264SeqWidthMBs"); OFF(S, picture_height_in_mbs, "vaH264SeqHeightMBs");
	OFF(S, seq_fields, "vaH264SeqFields");
	BIT(S, seq_fields, chroma_format_idc, "vaH264SeqChromaFormatBit"); BIT(S, seq_fields, frame_mbs_only_flag, "vaH264SeqFrameMBsOnlyBit");
	BIT(S, seq_fields, direct_8x8_inference_flag, "vaH264SeqDirect8x8Bit"); BIT(S, seq_fields, log2_max_frame_num_minus4, "vaH264SeqLog2MaxFrameNumBit");
	BIT(S, seq_fields, pic_order_cnt_type, "vaH264SeqPOCTypeBit"); BIT(S, seq_fields, log2_max_pic_order_cnt_lsb_minus4, "vaH264SeqLog2MaxPOCLsbBit");
	OFF(S, frame_cropping_flag, "vaH264SeqCropping"); OFF(S, frame_crop_right_offset, "vaH264SeqCropRight"); OFF(S, frame_crop_bottom_offset, "vaH264SeqCropBottom");
	OFF(S, vui_parameters_present_flag, "vaH264SeqVUI"); OFF(S, vui_fields, "vaH264SeqVUIFields");
	BIT(S, vui_fields, timing_info_present_flag, "vaH264SeqTimingBit"); BIT(S, vui_fields, fixed_frame_rate_flag, "vaH264SeqFixedRateBit");
	BIT(S, vui_fields, bitstream_restriction_flag, "vaH264SeqRestrictionBit");
	BIT(S, vui_fields, log2_max_mv_length_horizontal, "vaH264SeqMVHorBit"); BIT(S, vui_fields, log2_max_mv_length_vertical, "vaH264SeqMVVerBit");
	BIT(S, vui_fields, motion_vectors_over_pic_boundaries_flag, "vaH264SeqMVBoundBit");
	OFF(S, num_units_in_tick, "vaH264SeqUnitsInTick"); OFF(S, time_scale, "vaH264SeqTimeScale");
	typedef VAEncPictureParameterBufferH264 P;
	SZ(P, "vaSizeH264Pic");
	OFF(P, CurrPic, "vaH264PicCurr"); OFF(P, ReferenceFrames, "vaH264PicRefs"); OFF(P, coded_buf, "vaH264PicCodedBuf");
	OFF(P, pic_parameter_set_id, "vaH264PicPPSID"); OFF(P, seq_parameter_set_id, "vaH264PicSPSID"); OFF(P, last_picture, "vaH264PicLast");
	OFF(P, frame_num, "vaH264PicFrameNum"); OFF(P, pic_init_qp, "vaH264PicInitQP");
	OFF(P, num_ref_idx_l0_active_minus1, "vaH264PicNumRefL0"); OFF(P, num_ref_idx_l1_active_minus1, "vaH264PicNumRefL1");
	OFF(P, pic_fields, "vaH264PicFields");
	BIT(P, pic_fields, idr_pic_flag, "vaH264PicIDRBit"); BIT(P, pic_fields, reference_pic_flag, "vaH264PicRefBit");
	BIT(P, pic_fields, entropy_coding_mode_flag, "vaH264PicCABACBit"); BIT(P, pic_fields, transform_8x8_mode_flag, "vaH264PicT8x8Bit");
	BIT(P, pic_fields, deblocking_filter_control_present_flag, "vaH264PicDeblockCtlBit");
	typedef VAEncSliceParameterBufferH264 L;
	SZ(L, "vaSizeH264Slice");
	OFF(L, macroblock_address, "vaH264SliceMBAddr"); OFF(L, num_macroblocks, "vaH264SliceNumMBs"); OFF(L, macroblock_info, "vaH264SliceMBInfo");
	OFF(L, slice_type, "vaH264SliceType"); OFF(L, pic_parameter_set_id, "vaH264SlicePPSID"); OFF(L, idr_pic_id, "vaH264SliceIDRID");
	OFF(L, pic_order_cnt_lsb, "vaH264SlicePOCLsb"); OFF(L, direct_spatial_mv_pred_flag, "vaH264SliceDirectSpatial");
	OFF(L, num_ref_idx_active_override_flag, "vaH264SliceOverride");
	OFF(L, num_ref_idx_l0_active_minus1, "vaH264SliceNumRefL0"); OFF(L, num_ref_idx_l1_active_minus1, "vaH264SliceNumRefL1");
	OFF(L, RefPicList0, "vaH264SliceRefList0"); OFF(L, RefPicList1, "vaH264SliceRefList1");
	OFF(L, slice_qp_delta, "vaH264SliceQPDelta");

	/* HEVC */
	SZ(VAPictureHEVC, "vaSizePictureHEVC");
	OFF(VAPictureHEVC, picture_id, "vaHEVCPicID"); OFF(VAPictureHEVC, pic_order_cnt, "vaHEVCPicPOC"); OFF(VAPictureHEVC, flags, "vaHEVCPicFlags");
	typedef VAEncSequenceParameterBufferHEVC HS;
	SZ(HS, "vaSizeHEVCSeq");
	OFF(HS, general_profile_idc, "vaHEVCSeqProfile"); OFF(HS, general_level_idc, "vaHEVCSeqLevel"); OFF(HS, general_tier_flag, "vaHEVCSeqTier");
	OFF(HS, intra_period, "vaHEVCSeqIntraPeriod"); OFF(HS, intra_idr_period, "vaHEVCSeqIDRPeriod"); OFF(HS, ip_period, "vaHEVCSeqIPPeriod");
	OFF(HS, pic_width_in_luma_samples, "vaHEVCSeqWidth"); OFF(HS, pic_height_in_luma_samples, "vaHEVCSeqHeight");
	OFF(HS, seq_fields, "vaHEVCSeqFields");
	BIT(HS, seq_fields, chroma_format_idc, "vaHEVCSeqChromaFormatBit"); BIT(HS, seq_fields, bit_depth_luma_minus8, "vaHEVCSeqLumaDepthBit"); BIT(HS, seq_fields, bit_depth_chroma_minus8, "vaHEVCSeqChromaDepthBit"); BIT(HS, seq_fields, amp_enabled_flag, "vaHEVCSeqAMPBit");
	BIT(HS, seq_fields, sample_adaptive_offset_enabled_flag, "vaHEVCSeqSAOBit"); BIT(HS, seq_fields, sps_temporal_mvp_enabled_flag, "vaHEVCSeqTMVPBit");
	BIT(HS, seq_fields, strong_intra_smoothing_enabled_flag, "vaHEVCSeqStrongIntraBit"); BIT(HS, seq_fields, low_delay_seq, "vaHEVCSeqLowDelayBit");
	OFF(HS, log2_min_luma_coding_block_size_minus3, "vaHEVCSeqLog2MinCB"); OFF(HS, log2_diff_max_min_luma_coding_block_size, "vaHEVCSeqLog2DiffCB");
	OFF(HS, log2_min_transform_block_size_minus2, "vaHEVCSeqLog2MinTB"); OFF(HS, log2_diff_max_min_transform_block_size, "vaHEVCSeqLog2DiffTB");
	OFF(HS, max_transform_hierarchy_depth_inter, "vaHEVCSeqTHDInter"); OFF(HS, max_transform_hierarchy_depth_intra, "vaHEVCSeqTHDIntra");
	OFF(HS, vui_parameters_present_flag, "vaHEVCSeqVUI"); OFF(HS, vui_fields, "vaHEVCSeqVUIFields");
	BIT(HS, vui_fields, vui_timing_info_present_flag, "vaHEVCSeqTimingBit"); BIT(HS, vui_fields, bitstream_restriction_flag, "vaHEVCSeqRestrictionBit");
	BIT(HS, vui_fields, motion_vectors_over_pic_boundaries_flag, "vaHEVCSeqMVBoundBit");
	BIT(HS, vui_fields, log2_max_mv_length_horizontal, "vaHEVCSeqMVHorBit"); BIT(HS, vui_fields, log2_max_mv_length_vertical, "vaHEVCSeqMVVerBit");
	OFF(HS, vui_num_units_in_tick, "vaHEVCSeqUnitsInTick"); OFF(HS, vui_time_scale, "vaHEVCSeqTimeScale");
	typedef VAEncPictureParameterBufferHEVC HP;
	SZ(HP, "vaSizeHEVCPic");
	OFF(HP, decoded_curr_pic, "vaHEVCPicCurr"); OFF(HP, reference_frames, "vaHEVCPicRefs"); OFF(HP, coded_buf, "vaHEVCPicCodedBuf");
	OFF(HP, collocated_ref_pic_index, "vaHEVCPicCollocated"); OFF(HP, last_picture, "vaHEVCPicLast"); OFF(HP, pic_init_qp, "vaHEVCPicInitQP");
	OFF(HP, diff_cu_qp_delta_depth, "vaHEVCPicDiffCUQPDepth");
	OFF(HP, num_ref_idx_l0_default_active_minus1, "vaHEVCPicNumRefL0"); OFF(HP, num_ref_idx_l1_default_active_minus1, "vaHEVCPicNumRefL1");
	OFF(HP, slice_pic_parameter_set_id, "vaHEVCPicPPSID"); OFF(HP, nal_unit_type, "vaHEVCPicNALType");
	OFF(HP, pic_fields, "vaHEVCPicFields");
	BIT(HP, pic_fields, idr_pic_flag, "vaHEVCPicIDRBit"); BIT(HP, pic_fields, coding_type, "vaHEVCPicCodingTypeBit");
	BIT(HP, pic_fields, reference_pic_flag, "vaHEVCPicRefBit"); BIT(HP, pic_fields, cu_qp_delta_enabled_flag, "vaHEVCPicCUQPDeltaBit");
	BIT(HP, pic_fields, transform_skip_enabled_flag, "vaHEVCPicTransformSkipBit");
	BIT(HP, pic_fields, sign_data_hiding_enabled_flag, "vaHEVCPicSignHidingBit");
	BIT(HP, pic_fields, pps_loop_filter_across_slices_enabled_flag, "vaHEVCPicLFAcrossSlicesBit");
	typedef VAEncSliceParameterBufferHEVC HL;
	SZ(HL, "vaSizeHEVCSlice");
	OFF(HL, slice_segment_address, "vaHEVCSliceAddr"); OFF(HL, num_ctu_in_slice, "vaHEVCSliceNumCTUs"); OFF(HL, slice_type, "vaHEVCSliceType");
	OFF(HL, slice_pic_parameter_set_id, "vaHEVCSlicePPSID");
	OFF(HL, num_ref_idx_l0_active_minus1, "vaHEVCSliceNumRefL0"); OFF(HL, num_ref_idx_l1_active_minus1, "vaHEVCSliceNumRefL1");
	OFF(HL, ref_pic_list0, "vaHEVCSliceRefList0"); OFF(HL, ref_pic_list1, "vaHEVCSliceRefList1");
	OFF(HL, max_num_merge_cand, "vaHEVCSliceMaxMerge"); OFF(HL, slice_qp_delta, "vaHEVCSliceQPDelta");
	OFF(HL, slice_fields, "vaHEVCSliceFields");
	BIT(HL, slice_fields, last_slice_of_pic_flag, "vaHEVCSliceLastBit"); BIT(HL, slice_fields, slice_temporal_mvp_enabled_flag, "vaHEVCSliceTMVPBit");
	BIT(HL, slice_fields, slice_sao_luma_flag, "vaHEVCSliceSAOLumaBit"); BIT(HL, slice_fields, slice_sao_chroma_flag, "vaHEVCSliceSAOChromaBit");
	BIT(HL, slice_fields, num_ref_idx_active_override_flag, "vaHEVCSliceOverrideBit");
	BIT(HL, slice_fields, slice_loop_filter_across_slices_enabled_flag, "vaHEVCSliceLFAcrossBit");
	BIT(HL, slice_fields, collocated_from_l0_flag, "vaHEVCSliceColFromL0Bit");

	/* AV1 */
	C(VAProfileAV1Profile0, "vaProfileAV1Profile0");
	typedef VAEncSequenceParameterBufferAV1 AS;
	SZ(AS, "vaSizeAV1Seq");
	OFF(AS, seq_profile, "vaAV1SeqProfile"); OFF(AS, seq_level_idx, "vaAV1SeqLevel"); OFF(AS, seq_tier, "vaAV1SeqTier");
	OFF(AS, intra_period, "vaAV1SeqIntraPeriod"); OFF(AS, ip_period, "vaAV1SeqIPPeriod");
	OFF(AS, seq_fields, "vaAV1SeqFields"); OFF(AS, order_hint_bits_minus_1, "vaAV1SeqOrderHintBits");
	BIT(AS, seq_fields, enable_order_hint, "vaAV1SeqOrderHintBit"); BIT(AS, seq_fields, bit_depth_minus8, "vaAV1SeqDepthBit"); BIT(AS, seq_fields, enable_cdef, "vaAV1SeqCDEFBit");
	typedef VAEncPictureParameterBufferAV1 AP;
	SZ(AP, "vaSizeAV1Pic");
	OFF(AP, frame_width_minus_1, "vaAV1PicWidth"); OFF(AP, frame_height_minus_1, "vaAV1PicHeight");
	OFF(AP, reconstructed_frame, "vaAV1PicRecon"); OFF(AP, coded_buf, "vaAV1PicCodedBuf");
	OFF(AP, reference_frames, "vaAV1PicRefs"); OFF(AP, ref_frame_idx, "vaAV1PicRefIdx");
	OFF(AP, primary_ref_frame, "vaAV1PicPrimaryRef"); OFF(AP, order_hint, "vaAV1PicOrderHint");
	OFF(AP, refresh_frame_flags, "vaAV1PicRefresh"); OFF(AP, ref_frame_ctrl_l0, "vaAV1PicRefCtrlL0");
	OFF(AP, picture_flags, "vaAV1PicFlags");
	BIT(AP, picture_flags, frame_type, "vaAV1PicFrameTypeBit"); BIT(AP, picture_flags, error_resilient_mode, "vaAV1PicErrorResilientBit");
	OFF(AP, base_qindex, "vaAV1PicBaseQIndex"); OFF(AP, min_base_qindex, "vaAV1PicMinQIndex"); OFF(AP, max_base_qindex, "vaAV1PicMaxQIndex");
	OFF(AP, mode_control_flags, "vaAV1PicModeControl"); BIT(AP, mode_control_flags, tx_mode, "vaAV1PicTxModeBit");
	OFF(AP, tile_cols, "vaAV1PicTileCols"); OFF(AP, tile_rows, "vaAV1PicTileRows");
	OFF(AP, width_in_sbs_minus_1, "vaAV1PicWidthSBs"); OFF(AP, height_in_sbs_minus_1, "vaAV1PicHeightSBs");
	OFF(AP, bit_offset_qindex, "vaAV1PicBitOffsetQIndex"); OFF(AP, bit_offset_segmentation, "vaAV1PicBitOffsetSeg");
	OFF(AP, bit_offset_loopfilter_params, "vaAV1PicBitOffsetLF"); OFF(AP, bit_offset_cdef_params, "vaAV1PicBitOffsetCDEF");
	OFF(AP, size_in_bits_cdef_params, "vaAV1PicCDEFBits"); OFF(AP, byte_offset_frame_hdr_obu_size, "vaAV1PicOBUSizeOffset");
	OFF(AP, size_in_bits_frame_hdr_obu, "vaAV1PicFrameHdrBits"); OFF(AP, tile_group_obu_hdr_info, "vaAV1PicTGHeader");
	{ AP p; memset(&p, 0, sizeof p); p.tile_group_obu_hdr_info.bits.obu_has_size_field = 1; printf("\t%s = %d\n", "vaAV1TGHasSizeBit", ffs(p.tile_group_obu_hdr_info.value) - 1); }
	{ VARefFrameCtrlAV1 c; c.value = 0; c.fields.search_idx0 = 1; printf("\t%s = %d\n", "vaAV1SearchIdx0Bit", ffs(c.value) - 1); }
	SZ(VAEncTileGroupBufferAV1, "vaSizeAV1TileGroup");

	/* HEVC decoding. */
	C(VAEntrypointVLD, "vaEntrypointVLD"); C(VAPictureParameterBufferType, "vaPictureParameterBufferType"); C(VAIQMatrixBufferType, "vaIQMatrixBufferType");
	C(VASliceParameterBufferType, "vaSliceParameterBufferType"); C(VASliceDataBufferType, "vaSliceDataBufferType"); C(VA_SLICE_DATA_FLAG_ALL, "vaSliceDataFlagAll");
	C(VA_PICTURE_HEVC_LONG_TERM_REFERENCE, "vaPictureHEVCLongTerm"); C(VA_PICTURE_HEVC_RPS_LT_CURR, "vaPictureHEVCLtCurr");
	typedef VAPictureParameterBufferHEVC DP;
	SZ(DP, "vaSizeHEVCDecPic"); OFF(DP, ReferenceFrames, "vaHEVCDecPicRefs"); OFF(DP, pic_width_in_luma_samples, "vaHEVCDecPicWidth");
	OFF(DP, pic_fields, "vaHEVCDecPicFields"); OFF(DP, sps_max_dec_pic_buffering_minus1, "vaHEVCDecPicMaxDecPicBuf");
	OFF(DP, init_qp_minus26, "vaHEVCDecPicInitQP"); OFF(DP, num_tile_rows_minus1, "vaHEVCDecPicTileRows");
	OFF(DP, column_width_minus1, "vaHEVCDecPicColumnWidths"); OFF(DP, row_height_minus1, "vaHEVCDecPicRowHeights");
	OFF(DP, slice_parsing_fields, "vaHEVCDecPicSliceFields"); OFF(DP, log2_max_pic_order_cnt_lsb_minus4, "vaHEVCDecPicLog2MaxPOCLsb");
	OFF(DP, num_extra_slice_header_bits, "vaHEVCDecPicExtraBits"); OFF(DP, st_rps_bits, "vaHEVCDecPicStRPSBits");
	BIT(DP, pic_fields, chroma_format_idc, "vaHEVCDecChromaFormatBit"); BIT(DP, pic_fields, separate_colour_plane_flag, "vaHEVCDecSepColourBit");
	BIT(DP, pic_fields, pcm_enabled_flag, "vaHEVCDecPCMBit"); BIT(DP, pic_fields, scaling_list_enabled_flag, "vaHEVCDecScalingBit");
	BIT(DP, pic_fields, transform_skip_enabled_flag, "vaHEVCDecTransformSkipBit"); BIT(DP, pic_fields, amp_enabled_flag, "vaHEVCDecAMPBit");
	BIT(DP, pic_fields, strong_intra_smoothing_enabled_flag, "vaHEVCDecStrongIntraBit"); BIT(DP, pic_fields, sign_data_hiding_enabled_flag, "vaHEVCDecSignHidingBit");
	BIT(DP, pic_fields, constrained_intra_pred_flag, "vaHEVCDecConstrainedIntraBit"); BIT(DP, pic_fields, cu_qp_delta_enabled_flag, "vaHEVCDecCUQPDeltaBit");
	BIT(DP, pic_fields, weighted_pred_flag, "vaHEVCDecWeightedPredBit"); BIT(DP, pic_fields, weighted_bipred_flag, "vaHEVCDecWeightedBipredBit");
	BIT(DP, pic_fields, transquant_bypass_enabled_flag, "vaHEVCDecBypassBit"); BIT(DP, pic_fields, tiles_enabled_flag, "vaHEVCDecTilesBit");
	BIT(DP, pic_fields, entropy_coding_sync_enabled_flag, "vaHEVCDecEntropySyncBit"); BIT(DP, pic_fields, pps_loop_filter_across_slices_enabled_flag, "vaHEVCDecLFAcrossSlicesBit");
	BIT(DP, pic_fields, loop_filter_across_tiles_enabled_flag, "vaHEVCDecLFAcrossTilesBit"); BIT(DP, pic_fields, pcm_loop_filter_disabled_flag, "vaHEVCDecPCMLFDisabledBit");
	BIT(DP, slice_parsing_fields, lists_modification_present_flag, "vaHEVCDecListsModBit"); BIT(DP, slice_parsing_fields, long_term_ref_pics_present_flag, "vaHEVCDecLTRefsBit");
	BIT(DP, slice_parsing_fields, sps_temporal_mvp_enabled_flag, "vaHEVCDecTMVPBit"); BIT(DP, slice_parsing_fields, cabac_init_present_flag, "vaHEVCDecCabacInitBit");
	BIT(DP, slice_parsing_fields, output_flag_present_flag, "vaHEVCDecOutputFlagBit"); BIT(DP, slice_parsing_fields, dependent_slice_segments_enabled_flag, "vaHEVCDecDependentBit");
	BIT(DP, slice_parsing_fields, pps_slice_chroma_qp_offsets_present_flag, "vaHEVCDecSliceChromaQPBit"); BIT(DP, slice_parsing_fields, sample_adaptive_offset_enabled_flag, "vaHEVCDecSAOBit");
	BIT(DP, slice_parsing_fields, deblocking_filter_override_enabled_flag, "vaHEVCDecDeblockOverrideBit"); BIT(DP, slice_parsing_fields, pps_disable_deblocking_filter_flag, "vaHEVCDecDeblockDisabledBit");
	BIT(DP, slice_parsing_fields, slice_segment_header_extension_present_flag, "vaHEVCDecHeaderExtBit"); BIT(DP, slice_parsing_fields, RapPicFlag, "vaHEVCDecRapBit");
	BIT(DP, slice_parsing_fields, IdrPicFlag, "vaHEVCDecIdrBit"); BIT(DP, slice_parsing_fields, IntraPicFlag, "vaHEVCDecIntraBit");
	typedef VASliceParameterBufferHEVC DS;
	SZ(DS, "vaSizeHEVCDecSlice"); OFF(DS, RefPicList, "vaHEVCDecSliceRefs"); OFF(DS, LongSliceFlags, "vaHEVCDecSliceFlags");
	OFF(DS, collocated_ref_idx, "vaHEVCDecSliceColRefIdx"); OFF(DS, delta_chroma_log2_weight_denom, "vaHEVCDecSliceChromaDenom");
	OFF(DS, delta_luma_weight_l0, "vaHEVCDecSliceWeightsL0"); OFF(DS, ChromaOffsetL1, "vaHEVCDecSliceChromaOffsetL1");
	OFF(DS, five_minus_max_num_merge_cand, "vaHEVCDecSliceMaxMerge"); OFF(DS, num_entry_point_offsets, "vaHEVCDecSliceEntryPoints");
	OFF(DS, slice_data_num_emu_prevn_bytes, "vaHEVCDecSliceEmuBytes");
#define LBIT(f, n) do { DS s; memset(&s, 0, sizeof s); s.LongSliceFlags.fields.f = 1; printf("\t%s = %d\n", n, ffs(s.LongSliceFlags.value) - 1); } while (0)
	LBIT(LastSliceOfPic, "vaHEVCDecSliceLastBit"); LBIT(dependent_slice_segment_flag, "vaHEVCDecSliceDependentBit");
	LBIT(slice_type, "vaHEVCDecSliceTypeBit"); LBIT(color_plane_id, "vaHEVCDecSliceColourPlaneBit");
	LBIT(slice_sao_luma_flag, "vaHEVCDecSliceSAOLumaBit"); LBIT(slice_sao_chroma_flag, "vaHEVCDecSliceSAOChromaBit");
	LBIT(mvd_l1_zero_flag, "vaHEVCDecSliceMvdL1ZeroBit"); LBIT(cabac_init_flag, "vaHEVCDecSliceCabacInitBit");
	LBIT(slice_temporal_mvp_enabled_flag, "vaHEVCDecSliceTMVPBit"); LBIT(slice_deblocking_filter_disabled_flag, "vaHEVCDecSliceDeblockOffBit");
	LBIT(collocated_from_l0_flag, "vaHEVCDecSliceColFromL0Bit"); LBIT(slice_loop_filter_across_slices_enabled_flag, "vaHEVCDecSliceLFAcrossBit");
	typedef VAIQMatrixBufferHEVC DQ;
	SZ(DQ, "vaSizeHEVCIQ"); OFF(DQ, ScalingList32x32, "vaHEVCIQ32"); OFF(DQ, ScalingListDC32x32, "vaHEVCIQDC32");
	/* MPEG-2 decoding */
	C(VAProfileMPEG2Main, "vaProfileMPEG2Main");
	typedef VAPictureParameterBufferMPEG2 MP;
	SZ(MP, "vaSizeMPEG2Pic"); OFF(MP, forward_reference_picture, "vaMPEG2PicForward"); OFF(MP, picture_coding_type, "vaMPEG2PicType");
	OFF(MP, picture_coding_extension, "vaMPEG2PicExt");
	BIT(MP, picture_coding_extension, intra_dc_precision, "vaMPEG2DCPrecisionBit"); BIT(MP, picture_coding_extension, picture_structure, "vaMPEG2StructureBit");
	BIT(MP, picture_coding_extension, top_field_first, "vaMPEG2TFFBit"); BIT(MP, picture_coding_extension, frame_pred_frame_dct, "vaMPEG2FramePredBit");
	BIT(MP, picture_coding_extension, concealment_motion_vectors, "vaMPEG2ConcealmentBit"); BIT(MP, picture_coding_extension, q_scale_type, "vaMPEG2QScaleTypeBit");
	BIT(MP, picture_coding_extension, intra_vlc_format, "vaMPEG2IntraVLCBit"); BIT(MP, picture_coding_extension, alternate_scan, "vaMPEG2AltScanBit");
	BIT(MP, picture_coding_extension, repeat_first_field, "vaMPEG2RepeatFirstBit"); BIT(MP, picture_coding_extension, progressive_frame, "vaMPEG2ProgressiveBit");
	BIT(MP, picture_coding_extension, is_first_field, "vaMPEG2FirstFieldBit");
	typedef VAIQMatrixBufferMPEG2 MQ;
	SZ(MQ, "vaSizeMPEG2IQ"); OFF(MQ, intra_quantiser_matrix, "vaMPEG2IQIntra"); OFF(MQ, chroma_non_intra_quantiser_matrix, "vaMPEG2IQChromaNonIntra");
	typedef VASliceParameterBufferMPEG2 MS;
	SZ(MS, "vaSizeMPEG2Slice"); OFF(MS, macroblock_offset, "vaMPEG2SliceMBOffset"); OFF(MS, intra_slice_flag, "vaMPEG2SliceIntra");
	/* H.264 decoding */
	C(VAProfileH264Main, "vaProfileH264Main"); C(VAProfileH264ConstrainedBaseline, "vaProfileH264ConstrainedBaseline");
	C(VA_PICTURE_H264_TOP_FIELD, "vaPictureH264Top"); C(VA_PICTURE_H264_BOTTOM_FIELD, "vaPictureH264Bottom");
	C(VA_PICTURE_H264_LONG_TERM_REFERENCE, "vaPictureH264LongTerm");
	typedef VAPictureParameterBufferH264 DHP;
	SZ(DHP, "vaSizeH264DecPic"); OFF(DHP, ReferenceFrames, "vaH264DecPicRefs"); OFF(DHP, picture_width_in_mbs_minus1, "vaH264DecPicWidth");
	OFF(DHP, num_ref_frames, "vaH264DecPicNumRefFrames"); OFF(DHP, seq_fields, "vaH264DecPicSeqFields"); OFF(DHP, pic_init_qp_minus26, "vaH264DecPicInitQP");
	OFF(DHP, pic_fields, "vaH264DecPicPicFields"); OFF(DHP, frame_num, "vaH264DecPicFrameNum");
	BIT(DHP, seq_fields, chroma_format_idc, "vaH264ChromaFormatBit"); BIT(DHP, seq_fields, gaps_in_frame_num_value_allowed_flag, "vaH264GapsBit");
	BIT(DHP, seq_fields, frame_mbs_only_flag, "vaH264FrameMBsOnlyBit"); BIT(DHP, seq_fields, mb_adaptive_frame_field_flag, "vaH264MBAFFBit");
	BIT(DHP, seq_fields, direct_8x8_inference_flag, "vaH264Direct8x8Bit"); BIT(DHP, seq_fields, MinLumaBiPredSize8x8, "vaH264MinBiPred8x8Bit");
	BIT(DHP, seq_fields, log2_max_frame_num_minus4, "vaH264Log2MaxFrameNumBit"); BIT(DHP, seq_fields, pic_order_cnt_type, "vaH264POCTypeBit");
	BIT(DHP, seq_fields, log2_max_pic_order_cnt_lsb_minus4, "vaH264Log2MaxPOCLsbBit"); BIT(DHP, seq_fields, delta_pic_order_always_zero_flag, "vaH264DeltaPOCZeroBit");
	BIT(DHP, pic_fields, entropy_coding_mode_flag, "vaH264CABACBit"); BIT(DHP, pic_fields, weighted_pred_flag, "vaH264WeightedPredBit");
	BIT(DHP, pic_fields, weighted_bipred_idc, "vaH264WeightedBipredBit"); BIT(DHP, pic_fields, transform_8x8_mode_flag, "vaH264Transform8x8Bit");
	BIT(DHP, pic_fields, field_pic_flag, "vaH264FieldPicBit"); BIT(DHP, pic_fields, constrained_intra_pred_flag, "vaH264ConstrainedIntraBit");
	BIT(DHP, pic_fields, pic_order_present_flag, "vaH264POCPresentBit"); BIT(DHP, pic_fields, deblocking_filter_control_present_flag, "vaH264DeblockControlBit");
	BIT(DHP, pic_fields, redundant_pic_cnt_present_flag, "vaH264RedundantPicCntBit"); BIT(DHP, pic_fields, reference_pic_flag, "vaH264ReferenceBit");
	typedef VAIQMatrixBufferH264 DHQ;
	SZ(DHQ, "vaSizeH264IQ"); OFF(DHQ, ScalingList8x8, "vaH264IQ8x8");
	typedef VASliceParameterBufferH264 DHS;
	SZ(DHS, "vaSizeH264DecSlice"); OFF(DHS, slice_data_bit_offset, "vaH264DecSliceBitOffset"); OFF(DHS, slice_type, "vaH264DecSliceType");
	OFF(DHS, RefPicList0, "vaH264DecSliceRefs0"); OFF(DHS, RefPicList1, "vaH264DecSliceRefs1"); OFF(DHS, luma_log2_weight_denom, "vaH264DecSliceLumaDenom");
	OFF(DHS, luma_weight_l0, "vaH264DecSliceLumaWeightL0"); OFF(DHS, chroma_weight_l0_flag, "vaH264DecSliceChromaFlagL0"); OFF(DHS, chroma_weight_l0, "vaH264DecSliceChromaWeightL0");
	OFF(DHS, luma_weight_l1_flag, "vaH264DecSliceLumaFlagL1"); OFF(DHS, chroma_offset_l1, "vaH264DecSliceChromaOffsetL1");
	printf(")\n");
	return 0;
}
